api_platform:

    # The title of the API.
    title: 'TEST APP'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
#    swagger:
#        versions: [3]

    oauth:
        # To enable or disable oauth.
        enabled: true

        # The oauth client id.
        clientId: '123'

        # The oauth client secret.
        clientSecret: '123'

        # The oauth type.
        type: 'oauth2'

        # The oauth flow grant type.
        #        flow: 'password'
        flow: 'password'

        # The oauth token url.
        tokenUrl: '/token'

        # The oauth authentication url.
        authorizationUrl: '/oauth/v2/auth'

        # The oauth scopes.
        scopes: []

    swagger:
        # The active versions of OpenAPI to be exported or used in the swagger_ui. The first value is the default.
        versions: [ 2, 3 ]

        # The swagger api keys.
#        api_keys:
#            api_keys:
          # The name of the header or query parameter containing the api key.
#                name: blah
        # Whether the api key should be a query parameter or a header.
#                type: header
