security:
    enable_authenticator_manager: true

    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        App\Entity\User\User:
            algorithm: auto
            cost: 12

    providers:

        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
#            id: App\Security\UserProvider
            entity:
                class: App\Entity\User\User
                property: username
    firewalls:
        api_token:
            pattern: ^/api/token$
            security: false
        api:
             pattern: ^/api
             security: true
             stateless: true
             oauth2: true
             provider: app_user_provider
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
