version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: base1
      MYSQL_ROOT_PASSWORD: SevKav2020FedUniver
#    volumes:
#      - ./docker/db/data:/var/lib/mysql:rw
#      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - "3306"
#      - "3307:3306"
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
