oauth2:
    resource: '@LeagueOAuth2ServerBundle/Resources/config/routes.php'
    type: php

check_jwt:
    path: /check_jwt
    controller: App\Controller\CheckJWTController::__invoke

controllers:
    resource: ../src/Controller/
    type: attribute
